# WeatherML - Data Exploration

Use this notebook for exploratory data analysis and experimentation.

In [ ]:
import requests
import pandas as pd

# Location (Duluth, GA)
latitude = 34.0029
longitude = -84.1446

url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": latitude,
    "longitude": longitude,
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "apparent_temperature_max",   # target (keep)
        "apparent_temperature_min",
        "relative_humidity_2m_max",
        "relative_humidity_2m_min",
        "relative_humidity_2m_mean",
        "wind_speed_10m_max",
        "wind_gusts_10m_max",
        "wind_direction_10m_dominant",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "precipitation_hours",
        "shortwave_radiation_sum",
        "sunshine_duration",
        "weather_code"
    ],
    "temperature_unit": "celsius",
    "wind_speed_unit": "mph",
    "timezone": "auto"
}

response = requests.get(url, params=params)
data = response.json()

# Convert to DataFrame
df = pd.DataFrame(data["daily"])

# Create target (tomorrow’s apparent temp)
df["target"] = df["apparent_temperature_max"].shift(-1)

# Features and labels
X = df.drop(columns=["apparent_temperature_max", "target"])
y = df["target"]

df.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,relative_humidity_2m_max,relative_humidity_2m_min,relative_humidity_2m_mean,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,shortwave_radiation_sum,sunshine_duration,weather_code,target
0,2026-03-18,12.0,-1.2,5.0,10.0,-5.1,73,26,44,6.3,12.5,89,0.0,0.0,0.0,0.0,19.96,33651.93,3,17.0
1,2026-03-19,19.6,0.7,9.7,17.0,-3.0,64,26,43,7.4,12.6,302,0.0,0.0,0.0,0.0,21.23,34297.95,3,20.8
2,2026-03-20,22.8,6.5,15.0,20.8,3.9,63,29,47,8.6,18.1,238,0.0,0.0,0.0,0.0,22.88,39978.20,3,25.2
3,2026-03-21,26.1,14.6,19.9,25.2,13.3,77,38,58,9.6,25.9,266,0.0,0.0,0.0,0.0,19.02,40809.01,3,28.3
4,2026-03-22,28.8,16.2,22.0,28.3,16.5,89,33,62,11.3,24.4,264,0.1,0.0,0.0,1.0,20.65,33440.03,51,21.1

In [ ]:
import sys
import os

sys.path.append(os.path.abspath(".."))  # or "." depending on location

from scripts.fetch_data import fetch_data

latitude = 25.7617
longitude = 80.1918
df = fetch_data(latitude, longitude, start_date="2019-01-01", end_date="2023-12-31", save_csv=True, csv_path="../data/raw/daily_weather.csv")
df.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,relative_humidity_2m_max,relative_humidity_2m_min,relative_humidity_2m_mean,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,shortwave_radiation_sum,sunshine_duration,weather_code,target
0,2026-03-19,35.2,21.4,27.7,36.4,22.2,65,28,46,7.5,16.3,30,0.2,0.0,0.0,2.0,22.07,39212.05,3,31.3
1,2026-03-20,31.1,19.6,24.6,31.3,19.5,85,36,55,10.3,24.2,310,0.1,0.0,0.0,1.0,16.52,31675.80,3,29.2
2,2026-03-21,29.0,17.6,22.6,29.2,19.4,97,37,66,9.0,19.0,311,0.0,0.0,0.0,0.0,21.56,38802.53,3,29.7
3,2026-03-22,30.1,16.1,23.5,29.7,16.3,81,26,51,7.7,17.2,312,0.0,0.0,0.0,0.0,21.36,41174.55,3,33.2
4,2026-03-23,33.6,17.8,25.9,33.2,17.6,63,23,43,5.9,14.5,313,0.0,0.0,0.0,0.0,20.40,41358.05,2,35.7